
version: 2

models:
    - name: stg_jobsdb_data
      description: "A dbt model having the raw data of jobsdb"
      columns:
          - name: id
            description: "The primary key job"
            tests:
                - unique
                - not_null
